[package]
name = "verneuil"
version = "0.1.0"
description = "A sqlite VFS for asynchronous replication to S3-compatible blob stores"
license = "MIT"
repository = "https://github.com/backtrace-labs/verneuil"
authors = ["Backtrace I/O <team@backtrace.io>"]
edition = "2018"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[features]
default = ["verneuil_vendor_sqlite"]
verneuil_vendor_sqlite = []
verneuil_test_vfs = ["blake2b_simd"]  # Build an archive for sqlite3 tests.
verneuil_test_minio = []  # Publish data to 127.0.0.1:7777
verneuil_test_validate_writes = ["verneuil_test_vfs"]  # Validate snapshots after writes
verneuil_test_validate_reads = ["verneuil_test_vfs"]  # Validate snapshots after reads as well (extra slow)
verneuil_test_validate_all = ["verneuil_test_validate_writes", "verneuil_test_validate_reads"]

[dependencies]
# We use blake2b to compare the actual db file and our replicated snapshot,
# but only during tests.
blake2b_simd = { version = "0.5", optional = true }
crossbeam-channel = "0.5"
lazy_static = "1"
percent-encoding = "2"
prost = "0.7"
rand = "0.8"
regex = "1"
rust-s3 = { version = "0.27.0-rc4", default-features = false, features = ["sync-rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
umash = "0.1.2"

[build-dependencies]
cc = "1"
