[package]
name = "verneuil"
version = "0.1.0"
description = "A sqlite VFS for asynchronous replication to S3-compatible blob stores"
license = "MIT"
repository = "https://github.com/backtrace-labs/verneuil"
authors = ["Backtrace I/O <team@backtrace.io>"]
edition = "2018"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[features]
default = ["verneuil_vendor_sqlite"]
verneuil_vendor_sqlite = []
verneuil_test_vfs = ["blake2b_simd"]  # Build an archive for sqlite3 tests.

[dependencies]
# We use blake2b to compare the actual db file and our replicated snapshot,
# but only during tests.
blake2b_simd = { version = "0.5", optional = true }
lazy_static = "1"
percent-encoding = "2"
prost = "0.7"
regex = "1"
tempfile = "3"
umash = "0.1.2"

[build-dependencies]
cc = "1"
