[package]
name = "verneuil"
version = "0.1.0"
description = "A sqlite VFS for asynchronous replication to S3-compatible blob stores"
license = "MIT"
repository = "https://github.com/backtrace-labs/verneuil"
authors = ["Backtrace I/O <team@backtrace.io>"]
edition = "2018"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[features]
default = ["verneuil_vendor_sqlite"]
verneuil_vendor_sqlite = []
verneuil_test_vfs = []  # Build an archive for sqlite3 tests.

[dependencies]
lazy_static = "1"
prost = "0.7"

[build-dependencies]
cc = "1"
